apiVersion: batch/v1
kind: Job
metadata:
  name: rdatamodeler
spec:
  template:
    spec:
      containers:
      - name: main
        image: xnonr/rdatamodeler
        command: []
        args: []
        env:
        - name: auto
          value: "TRUE"
        volumeMounts:
        - mountPath: /src/commands.csv
          name: commandfile
      volumes:
      - name: commandfile
        hostPath:
          path: /home/kubedge/proj/jbrette/K8s-RDataModeler/simple/commands.csv
          type: File
      restartPolicy: Never
  backoffLimit: 4
